use_frameworks!

target 'KFXCellularViewData_Example' do
  pod 'KFXCellularViewData', :path => '../'

## Sources
### If using private pods
source 'https://kfxtech@bitbucket.org/kfx_pods/kfxsharedspecs.git'

pod 'KFXUtilities', '>= 2.0.0'
pod 'KFXAdditions'
pod 'KFXAbstracts'


### If using from trunk
source 'http://github.com/Cocoapods/Specs.git'


  
  target 'KFXCellularViewData_Tests' do
    inherit! :search_paths

    
  end
end
