# use_frameworks!
platform :ios, '8.0'

target 'KFXCellularViewData_Example' do
  pod 'KFXCellularViewData', :path => '../'

  pod 'KFXUtilities'
  pod 'KFXAdditions'
  pod 'KFXAbstracts'

  target 'KFXCellularViewData_Tests' do
    inherit! :search_paths
  end
end
